const KEYS = [
  'REACT_APP_API_BASE',
  'REACT_APP_BACKEND_URL',
  'REACT_APP_FRONTEND_URL',
  'REACT_APP_WS_URL',
  'REACT_APP_NODE_ENV',
  'REACT_APP_NEXT_TELEMETRY_DISABLED',
  'REACT_APP_ENABLE_SOURCE_MAPS',
  'REACT_APP_PORT',
  'REACT_APP_TRUST_PROXY',
  'REACT_APP_LOG_LEVEL',
  'REACT_APP_HEALTHCHECK_PATH',
  'REACT_APP_FEATURE_FLAGS',
  'REACT_APP_EXPERIMENTS_ENABLED',
];

// PUBLIC_INTERFACE
export function getEnv() {
  const env = {};
  KEYS.forEach((k) => {
    env[k] = process.env[k];
  });
  return env;
}
